name: Publish to Comfy registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - "pyproject.toml"

permissions:
  issues: write

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'xmarre' }}
    steps:
      - name: Check out code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
          submodules: true
      - name: Publish Custom Node
        uses: Comfy-Org/publish-node-action@0eb6cd742945443bee7f79eeddd4f732780029a1 # v1
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
